file:
  upload-path: D:\uploads

spring:
  web:
    resources:
      static-locations: classpath:/static/, file:${file.upload-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

minio:
  endpoint: http://115.29.200.66:9000
  accessKey: admin
  secretKey: admin123