spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0 # Redis 数据库的索引·，不配置默认为 0
      password:     # Redis 服务器密码 默认为空
      lettuce:
        pool:
          min-idle: 10 # 连接池中的最小空闲连接数，默认为 0
          max-idle: 20 # 连接池中的最大空闲连接数，默认为 8
          max-active: 100 # 连接池中的最大连接数，默认为 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

ychen:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSid: 2c94811c9035ff9f0192adc2d5ce7ce2
      accountToken: 1ce6ac67a4124fd09efd2f47fb37ddc0
      appId: 2c94811c9035ff9f0192adc2d8677ce9
      templateId: 1

logging:
  level:
    com.baomidou.mybatisplus.samples: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operation-sorter: alpha
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        packages-to-scan: top.ychen.springboot.redis.controller

  knife4j:
    enable: true
    setting:
      language: zh_cn
    basic:
      enable: true
      username: admin
      password: 123456