logging:
  file:
#    path: ./logs
    name: ./logs/spring-boot-log.log
  level:
    root: INFO
    top.ychen.springboot.logging.controller: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 10
  pattern:
    console: '%yellow(%d){yyyy-MM-dd HH:mm:ss} %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n"
